import "./src/js/autocomplete"
import "./src/js/datetimepicker"
import "./src/js/collection"
import "./src/js/collection_contact"
import "./src/js/ajax_submit"
import "./src/js/dependent"
import "./src/js/icon_type"
import "./src/js/treeselect"
import "./src/js/number_spin"

import "./src/css/collection_contact.css"
import "./src/css/collection.css"
import "./src/css/icon_type.css"
